[package]
name = "mev-inspect"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
# ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "fix/generic-decode" }
ethers = { path = "/Users/Georgios/paradigm/ethers-rs/ethers" }
serde_json = "1.0.59"
once_cell = "1.4.1"
itertools = "0.9.0"
tokio = { version = "0.2", features = ["macros"] }
anyhow = "1.0.34"
rustc-hex = "2.1.0"

[dev-dependencies]
rustc-hex = "2.1.0"
